# Site settings
title: OData .NET Core Libraries
email: odatafeedback@microsoft.com
description: > # this means to ignore newlines until "baseurl:"
  This site contains samples covering basic and advanced OData scenarios for
  ODataLib, EdmLib, OData Client for .NET, and OData v4 Client Code Generator.
baseurl: "/odata.net" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  odata

permalink: /:categories/:title/

# Build settings
markdown: kramdown
